version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: operations:1:1
      KAFKA_ADVERTISED_PORT: 9092
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    ports:
        - "9200:9200"
        - "9300:9300"
  db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "@OpO12Wsfkfrsfg"
      ACCEPT_EULA: "Y"
  web:
    build: .
    ports:
      - "8085:80"
    container_name: UserPermission
    environment:
      URLKAFKA: kafka:9092
      ELASTICSEARCH: localhost:9200
      TOPIC: operations
      DBCONNECTION: Server=db;Database=Permission;User=sa;Password=@OpO12Wsfkfrsfg;MultipleActiveResultSets=true;Trust Server Certificate=true
    depends_on:
      - kafka
      - elasticsearch
      - db